version: "3.9"

services:
  app:
    tty: true
    container_name: app
    image: nathansetyawan96/news-app:latest
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - api
    networks:
      - backend

  api:
    tty: true
    container_name: api
    image: nathansetyawan96/news-api:latest
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge
